controller_frequency: 10.0 # movebase以 3Hz 的频率发布 运动控制命令(cmd_vel)
planner_frequency: 0.5 # movebase 以 0.1Hz 规划一次新路径

recovery_behavior_enabled: true # 启用 自救行为
clearing_rotation_allowed: true # 启用 自动清理障碍标记

TrajectoryPlannerROS:
   max_vel_x: 0.80 # 最大x轴线速度 运动速度 0.325m/s
   min_vel_x: 0.10 # 最小x轴线速度 运动速度 0.085m/s
   max_vel_y: 0.0  # zero for a differential drive robot
   min_vel_y: 0.0
   max_vel_theta: 1.5
   min_vel_theta: -1.5
   min_in_place_vel_theta: 0.525
   escape_vel: -0.15
   acc_lim_x: 0.6
   acc_lim_y: 0.0  # zero for a differential drive robot
   acc_lim_theta: 0.8

   max_trans_vel: 0.5 # choose slightly less than the base's capability 
    #机器人最大平移速度的绝对值，单位为 m/s
   min_trans_vel: 0.1  # this is the min trans velocity when there is negligible rotational velocity 
    #机器人最小平移速度的绝对值，单位为 m/s



   holonomic_robot: false
   yaw_goal_tolerance: 0.35 # about -- degrees 目标位置的角度容忍度
   xy_goal_tolerance: 0.15  # 15 cm 目标位置的位置容忍度
   latch_xy_goal_tolerance: false
   path_distance_bias: 0.30
   goal_distance_bias: 0.60
   meter_scoring: true

   heading_lookahead: 0.325
   heading_scoring: true
   heading_scoring_timestep: 0.8
   occdist_scale: 0.05
   oscillation_reset_dist: 0.05
   publish_cost_grid_pc: false
   prune_plan: true

   sim_time: 1.5 # 预仿真时间，计算多长时间内的情况，影响连贯性
   sim_granularity: 0.025
   angular_sim_granularity: 0.025
   vx_samples: 25 # 线速度 采样点数量
   vy_samples: 0  # zero for a differential drive robot
   vtheta_samples: 50 # 角速度 采样点数量
   dwa: true
   simple_attractor: false